server:
  port: 8082
spring:
  application:
    name: product-service
  mongodb:
    uri: ${MONGODB_URI:mongodb://localhost:27017/productservice}
  web:
    error:
      include-message: always
      include-stacktrace: on_param
      include-binding-errors: always
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: your-super-secret-key-here-make-it-long-and-random
  expiration: 86400000